### ISSUE TITLE
Clear out Blogs that don't parse

### ISSUE THREAD

**Issue by sursh** [recursecenter/blaggregator#95]
Each registered blog is pinged, in order. This is the slowest (and most expensive) part of the crawling, and the biggest reason why Blaggregator costs me $30/mo to run. There are a LOT of blogs that aren't parsing, which really slows down the crawling. I've been ignoring this, but as blaggregator grows this is becoming a bigger issue. 

There are several possible ways to do this. One way: 
- each time a blog doesn't parse successfully, increment a counter
- after 3 days, email the blog owner with some troubleshooting suggestions (does it exist, does it parse, watch out for redirects, etc)
- after 6 days, remove the blog and email the blog owner (I believe this would also remove all associated Posts as well)

Thoughts?

**Comment by punchagan** [comment]
Woah! I didn't know it costed $30/m to run Blaggregator. Thanks for bearing the costs and keeping Blaggregator going, along with spending time maintaining the code! 

We could mark blogs as 'inactive' instead of removing them. 

Also, I wonder if it would be worth the effort to think of other ways to reduce the number of crawls, and number of blogs pinged per crawl. We could add a button for people to manually ask for a crawl of their blog and reduce the frequency of crawls to once an hour or even less.

**Comment by sursh** [comment]
All great suggestions. 




People who just published get antsy about their post not showing up within a few minutes, so a "crawl my blog now!" button or Zulip bot listener may be a good option to trigger a crawl of just their blog. Then I think we could get away with hourly. (In scheduler there's nothing in between every 10 and every 60. 



—

**Comment by punchagan** [comment]
We should look at the [new pricing options](https://blog.heroku.com/archives/2015/5/7/new-dyno-types-public-beta) and see if it makes sense to shift to them.  If you can share the current bill/usage information for the dynos, I'll have more data to look at. 

We may not be able to shift to the free plan (in the new plan) because it needs the dyno to sleep for at least 6 hours a day, but we could probably shift to the hobby plan which costs $7/dyno/month.

**Comment by punchagan** [comment]
Apart from #100 and #101, we could implement automatic deactivation of dead blogs.  This would reduce the current load by ~20%.  

An alternate idea would be to encourage bloggers to support [PubSubHubbub](https://en.wikipedia.org/wiki/PubSubHubbub) and use notifications from hubs instead of polling for changes. Wordpress, blogspot and medium already support this (about ~10% of our current blogs). It shouldn't be too hard to integrate with static site generators like Jekyll, Octopress and Nikola. 

But the biggest gains would be through async I/O workers.

**Comment by punchagan** [comment]
We have moved to crawling once an hour, instead of every 10 minutes and this is no longer as much of a problem.
